server {
  listen 3000;
  server_name _;

  location = /favicon.ico {
    alias /usr/share/nginx/html/assets/logos/logo.png;
    access_log off;
    log_not_found off;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ $uri/index.html /index.html =404;
  }

  include /etc/nginx/extra-conf.d/*.conf;
}
